"""agregar tablas de carrito y pedidos

Revision ID: 73361a5a8935
Revises: 9c5eda0bd1e2
Create Date: 2026-07-06 15:24:34.274503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73361a5a8935'
down_revision: Union[str, Sequence[str], None] = '9c5eda0bd1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
