"""Agregar relacion carrito a usuario

Revision ID: e59750d2d11a
Revises: 0cd4376e3090
Create Date: 2026-07-06 19:50:16.621617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59750d2d11a'
down_revision: Union[str, Sequence[str], None] = '0cd4376e3090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
